export const podcasts = [
  {
    id: "10716",
    title: "Something Was Wrong",
    description:
      "Something Was Wrong is an Iris Award-winning true-crime docuseries about the discovery, trauma, and recovery from shocking life events and abusive relationships.",
    seasons: 14,
    image: "podcast-img/something-was-wrong.png",
    genres: [1, 2],
    updated: "2022-11-03T07:00:00.000Z",
  },
  {
    id: "5675",
    title: "This Is Actually Happening",
    description:
      "What if your mother left to follow a cult… or you woke up in a morgue… or if your boat got caught in a storm and began to sink -- what would you do?   This is Actually Happening brings you extraordinary true stories of life-changing events told by the people who lived them. From a man who finds out a celebrity crush isn’t who she seems to a woman stranded in a Mexican desert fighting to survive, these stories will have you on the edge of your seat waiting to hear what happens next. New episodes come out every Tuesday for free. Listen 1-week early and to exclusive past episodes - all ad-free - with Wondery+ or Amazon Music with a Prime membership or Amazon Music Unlimited subscription.",
    seasons: 12,
    image: "podcast-img/this-is-actually-happening.png",
    genres: [2],
    updated: "2022-11-01T10:00:00.000Z",
  },
  {
    id: "5279",
    title: "American History Tellers",
    description:
      "The Cold War, Prohibition, the Gold Rush, the Space Race. Every part of your life - the words you speak, the ideas you share - can be traced to our history, but how well do you really know the stories that made America? We'll take you to the events, the times and the people that shaped our nation. And we'll show you how our history affected them, their families and affects you today. Hosted by Lindsay Graham (not the Senator). From Wondery, the network behind American Scandal, Tides of History, American Innovations and more. New episodes come out every Wednesday for free, with 1-week early access for Wondery+ subscribers. Listen ad-free on Wondery+ or on Amazon Music with a Prime membership or Amazon Music Unlimited subscription.",
    seasons: 51,
    image: "podcast-img/american-history-teller.png",
    genres: [3],
    updated: "2022-11-02T07:01:00.000Z",
  },
  {
    id: "10539",
    title: "Scamfluencers",
    description:
      "You never really know someone…especially online. In today’s world, the power of influence can be the quickest path to money and fame, and it often ends in ruin. These are the stories of the world’s most insidious Scamfluencers. And we are their prey. On Wondery’s new weekly series, join co-hosts Scaachi Koul and Sarah Hagi as they unpack epic stories of deception from the worlds of social media, fashion, finance, health, and wellness. These influencers claim to be everything from charismatic healers to trusted financial insiders to experts in dating. They cast spells over millions. Why do we believe them, and how does our culture allow them to thrive? From Black Swan Murder to a fake social media influencer to an audacious Hollywood Ponzi schemer, each season will take the listener along the twists and turns, the impact on victims, and what’s left when the facade falls away. New episodes come out every Monday for free, with 1-week early access for Wondery+ subscribers. Listen ad-free on Wondery+ or on Amazon Music with a Prime membership or Amazon Music Unlimited subscription.",
    seasons: 3,
    image: "podcast-img/scamfluencers.png",
    genres: [2],
    updated: "2022-10-24T07:01:00.000Z",
  },
  {
    id: "9177",
    title: "Killer Psyche",
    description:
      "When a shocking crime occurs, people ask “Why?” Was it about power, ego, or revenge? On Killer Psyche, retired FBI agent Candice DeLong draws on her decades of experience to reveal why these murderers and criminals committed these acts. She will reveal fascinating new details about what drove these people, including cases she was close to. Candice will share specific psychological methods and profiling techniques that experts use to understand the deepest part of the most complex, fascinating, and twisted minds, from the Unabomber to Dr. Death to El Chapo. Listen to new episodes 1-week early and to all episodes ad-free with Wondery+ or on Amazon Music with a Prime membership or Amazon Music Unlimited subscription. Join Wondery+ here: https://wondery.app.link/killerpsyche",
    seasons: 2,
    image: "podcast-img/killer-psyche.png",
    genres: [3, 2],
    updated: "2022-11-01T07:03:00.000Z",
  },
  {
    id: "6807",
    title: "Even the Rich",
    description:
      "Our lives can be crazy, but you can take a break from it all with Wondery’s new series, Even the Rich, where co-hosts Brooke Siffrinn and Aricia Skidmore-Williams pull back the curtain and chat about someone else’s craziness for a change. They tell stories about some of the greatest family dynasties in history, from the Murdochs to the Royals to the Carters (Jay-Z and Beyoncé, that is). Because as Queen Elizabeth once said, “A good gossip is a wonderful tonic.” New episodes come out every Tuesday for free. Wondery+ subscribers get early access to new full seasons and all episodes ad-free.",
    seasons: 33,
    image: "podcast-img/even-the-rich.png",
    genres: [4, 5, 3],
    updated: "2022-11-01T07:08:00.000Z",
  },
  {
    id: "8514",
    title: "Against The Odds",
    description:
      "Humans are resilient. In our toughest moments, we will fight, we will struggle, and we will triumph...often against the odds.  In this immersive series from Wondery, host-adventurers Mike Corey and Cassie De Pecol will share thrilling stories of survival. From the daring rescue of a soccer team trapped in an underwater cave in Thailand, to a woman taken hostage by Somali pirates, these stories made headlines around the world. AGAINST THE ODDS will make you feel as though you’re living these experiences with our heroes as they push themselves to their limits. New episodes come out every Tuesday for free, with 1-week early access for Wondery+ subscribers. Listen ad-free on Wondery+ or on Amazon Music with a Prime membership or Amazon Music Unlimited subscription.",
    seasons: 19,
    image: "podcast-img/against-the-odds.png",
    genres: [3],
    updated: "2022-11-01T07:01:00.000Z",
  },
  {
    id: "10276",
    title: "This Podcast Will Kill You",
    description:
      "This podcast might not actually kill you, but it covers so many things that can. Each episode tackles a different disease, from its history, to its biology, and finally, how scared you need to be. Ecologists and epidemiologists Erin Welsh and Erin Allmann Updyke make infectious diseases acceptable fodder for dinner party conversation and provide the perfect cocktail recipe to match.",
    seasons: 5,
    image: "podcast-img/this-podcast-will-kill-you.png",
    genres: [1],
    updated: "2022-10-25T07:01:00.000Z",
  },
  {
    id: "8860",
    title: "British Scandal",
    description:
      "In a country obsessed with gossip, the great and the good fear one thing more than any other - scandal. British scandals change the course of history. They bring down governments, overthrow the rich and cause the mighty to fall. Some are about sex, others about money. In the end, they’re all about power.  But often at the heart of a scandal, there are ordinary human stories, stories of those caught up in the swirl of outrage.  Who was really to blame for what happened? Why did they do it? And when all is said and done, did anything really change?    From the creators of Business Wars, American Scandal and Even The Rich, comes British Scandal. We tell the stories of the murkier side of the British elite, from Phone Hacking to Saville to Profumo who show us the reality of power, the price of pride and the failings of the great and good. Because sometimes the truth doesn’t set everyone free… New episodes come out every Wednesday for free, with 1-week early access for Wondery+ subscribers. Listen ad-free on Wondery+ or on Amazon Music with a Prime membership or Amazon Music Unlimited subscription.",
    seasons: 19,
    image: "podcast-img/british-scandal.png",
    genres: [2],
    updated: "2022-11-01T23:01:00.000Z",
  },
  {
    id: "5629",
    title: "Tides of History",
    description:
      "Everywhere around us are echoes of the past. Those echoes define the boundaries of states and countries, how we pray and how we fight. They determine what money we spend and how we earn it at work, what language we speak and how we raise our children. From Wondery, host Patrick Wyman, PhD (“Fall Of Rome”) helps us understand our world and how it got to be the way it is. New episodes come out Thursdays for free, with 1-week early access for Wondery+ subscribers. Listen ad-free on Wondery+ or on Amazon Music with a Prime membership or Amazon Music Unlimited subscription.",
    seasons: 5,
    image: "podcast-img/tides-of-history.png",
    genres: [3],
    updated: "2022-11-03T07:01:00.000Z",
  },
];

export const genres = [
  {
    id: 1,
    title: "Personal Growth",
    description:
      "Looking to improve yourself and reach your full potential? ...",
    shows: ["10716", "10276", "6756", "10660"],
  },
  {
    id: 2,
    title: "Investigative Journalism",
    description:
      "Looking for a collection of podcasts that will keep you on the edge of your seat? ...",
    shows: [
      "10716",
      "5675",
      "10539",
      "9177",
      "8860",
      "5012",
      "9054",
      "7654",
      "8256",
      "8291",
      "5718",
      "5276",
      "5964",
      "6465",
      "5320",
      "6451",
      "5692",
      "6430",
    ],
  },
  {
    id: 3,
    title: "History",
    description:
      "Experience the past like never before with our collection of history podcasts! ...",
    shows: [
      "5279",
      "9177",
      "6807",
      "8514",
      "5629",
      "8364",
      "5964",
      "9041",
      "5702",
      "5320",
      "6717",
      "5968",
      "8760",
    ],
  },
  {
    id: 4,
    title: "Comedy",
    description:
      "Get ready to laugh with our collection of comedy podcasts! ...",
    shows: ["6807"],
  },
  {
    id: 5,
    title: "Entertainment",
    description: "Entertainment lovers, get ready for a treat! ...",
    shows: ["6807", "6631", "8256", "6756", "5702", "9620", "10758"],
  },
  {
    id: 6,
    title: "Business",
    description:
      "For those who want to keep their finger on the pulse of the entertainment industry, ...",
    shows: ["8364", "6717", "8760"],
  },
  {
    id: 7,
    title: "Fiction",
    description:
      "Get ready to be transported to new worlds and lose yourself in captivating stories ...",
    shows: ["6631", "9664", "8188", "9702", "9695", "9994", "9263", "9666"],
  },
  {
    id: 8,
    title: "News",
    description:
      "Stay informed and on top of the latest events with our collection of current news podcasts. ...",
    shows: ["8291", "5718"],
  },
  {
    id: 9,
    title: "Kids and Family",
    description:
      "Bring some fun and learning to your family's ears with our collection of kids and family podcasts. ...",
    shows: [
      "8188",
      "9687",
      "9702",
      "9665",
      "10182",
      "9994",
      "9705",
      "10934",
      "9694",
      "9693",
      "9704",
      "9739",
      "9691",
    ],
  },
];

export const seasons = [
  {
    id: "10716",
    seasonDetails: [
      { title: "Season 1", episodes: 10 },
      { title: "Season 2", episodes: 8 },
      { title: "Season 3", episodes: 9 },
      { title: "Season 4", episodes: 7 },
      { title: "Season 5", episodes: 10 },
      { title: "Season 6", episodes: 7 },
      { title: "Season 7", episodes: 6 },
      { title: "Season 8", episodes: 6 },
      { title: "Season 9", episodes: 9 },
      { title: "Season 10", episodes: 10 },
      { title: "Season 11", episodes: 10 },
      { title: "Season 12", episodes: 6 },
      { title: "Season 13", episodes: 10 },
      { title: "Season 14", episodes: 4 },
    ],
  },
  {
    id: "5675",
    seasonDetails: Array.from({ length: 12 }, (_, i) => ({
      title: `Season ${i + 1}`,
      episodes: 10,
    })),
  },
  {
    id: "5279",
    seasonDetails: [
      { title: "Season 1: The Cold War", episodes: 7 },
      { title: "Season 2: Prohibition", episodes: 7 },
      { title: "Season 3: The Age of Jackson", episodes: 7 },
      { title: "Season 4: The Space Race", episodes: 4 },
      { title: "Season 5: American Revolution", episodes: 7 },
      { title: "Season 6: National Parks", episodes: 7 },
      { title: "Season 7: Civil Rights", episodes: 7 },
      { title: "Season 8: Political Parties", episodes: 7 },
      { title: "Season 9: The 1968 Chicago Protests", episodes: 4 },
      { title: "Season 10: The Great Depression", episodes: 7 },
      { title: "Season 11: J. Edgar Hoover's FBI", episodes: 7 },
      { title: "Season 12: Sponsored | American Epidemics", episodes: 2 },
      { title: "Season 13: Tulsa Race Massacre", episodes: 7 },
      { title: "Season 14: The Bastard Brigade", episodes: 7 },
      { title: "Season 15: Dutch Manhattan", episodes: 7 },
      { title: "Season 16: The Triangle Shirtwaist Factory Fire", episodes: 5 },
      { title: "Season 17: Kentucky Blood Feud", episodes: 2 },
      { title: "Season 18: California Water Wars", episodes: 6 },
      { title: "Season 19: What We Learned from the Spanish Flu", episodes: 1 },
      { title: "Season 20: Rebellion in the Early Republic", episodes: 7 },
      { title: "Season 21: The WWII Home Front", episodes: 2 },
      { title: "Season 22: The Space Race", episodes: 4 },
      { title: "Season 23: Stonewall", episodes: 5 },
      { title: "Season 24: The Gilded Age", episodes: 7 },
      { title: "Season 25: Political Parties", episodes: 6 },
      { title: "Season 26: The Supreme Court", episodes: 8 },
      { title: "Season 27: Coal Wars", episodes: 5 },
      { title: "Season 28: Traditions, Crisis, and Unity", episodes: 1 },
      { title: "Season 29: The Great Chicago Fire", episodes: 4 },
      { title: "Season 30: America's Monuments", episodes: 7 },
      { title: "Season 31: Bleeding Kansas", episodes: 5 },
      { title: "Season 32: The Mystery of D.B. Cooper", episodes: 1 },
      { title: "Season 33: Tulsa Race Massacre", episodes: 5 },
      { title: "Season 34: Lost Colony of Roanoke", episodes: 3 },
      { title: "Season 35: The Walker Affair", episodes: 3 },
      {
        title: "Season 36: The Fight for the First U.S. Olympics",
        episodes: 4,
      },
      { title: "Season 37: National Parks", episodes: 6 },
      { title: "Season 38: Roaring Twenties", episodes: 5 },
      { title: "Season 39: Traitors", episodes: 5 },
      { title: "Season 40: Philippine-American War", episodes: 5 },
      { title: "Season 41: Billy the Kid", episodes: 4 },
      { title: "Season 42: The Plot to Steal Lincoln's Body", episodes: 3 },
      { title: "Season 43: The Fight for Women's Suffrage", episodes: 6 },
      { title: "Season 44: Lewis and Clark", episodes: 4 },
      { title: "Season 45: The Great Mississippi Flood", episodes: 4 },
      { title: "Season 46: The Age of Jackson", episodes: 7 },
      { title: "Season 47: The Manson Murders", episodes: 3 },
      { title: "Season 48: Civil War", episodes: 8 },
      { title: "Season 49: The Walker Affair", episodes: 3 },
      { title: "Season 50: The Age of Pirates", episodes: 4 },
      { title: "Season 51: Yellow Fever Epidemic of 1793", episodes: 1 },
    ],
  },
  {
    id: "10539",
    seasonDetails: [
      { title: "Season 1", episodes: 8 },
      { title: "Season 2", episodes: 9 },
      { title: "Season 3", episodes: 9 },
    ],
  },
  {
    id: "9177",
    seasonDetails: [
      { title: "Season 1", episodes: 10 },
      { title: "Season 2", episodes: 10 },
    ],
  },
  {
    id: "6807",
    seasonDetails: [
      { title: "Season 1: From Commoner to Royalty", episodes: 5 },
      { title: "Season 2: A Real Life 'Succession' Story", episodes: 6 },
      { title: "Season 3: American Royalty", episodes: 5 },
      { title: "Season 4: The Gettys", episodes: 6 },
      { title: "Season 5: The House of Versace", episodes: 5 },
      { title: "Season 6: Chappaquiddick", episodes: 3 },
      { title: "Season 7: JFK Jr. and Carolyn Bessette", episodes: 3 },
      { title: "Season 8: #FreeBritney", episodes: 5 },
      { title: "Season 9: Diana to Meghan", episodes: 5 },
      {
        title: "Season 10: Brooke and Aricia's Big Rich Year-End Special",
        episodes: 1,
      },
      { title: "Season 11: Paris Hilton", episodes: 5 },
      { title: "Season 12: The Kardashians", episodes: 5 },
      { title: "Season 13: Oprah Presents Meghan and Harry", episodes: 1 },
      { title: "Season 14: JFK & Jackie", episodes: 4 },
      { title: "Season 15: American Royalty", episodes: 5 },
      { title: "Season 16: The Making of Madonna", episodes: 5 },
      { title: "Season 17: The Life & Loves of Elizabeth Taylor", episodes: 5 },
      { title: "Season 18: Back to Bennifer", episodes: 3 },
      { title: "Season 19: The Emancipation of Mariah Carey", episodes: 5 },
      { title: "Season 20: A Real Life 'Succession' Story", episodes: 5 },
      { title: "Season 21: Murder in the House of Gucci", episodes: 4 },
      { title: "Season 22: Blonde. Billionaire. Boss", episodes: 5 },
      { title: "Season 23: The Patty Hearst Story", episodes: 5 },
      { title: "Season 24: Janet vs The HalfTime Show", episodes: 3 },
      { title: "Season 25: The Kardashians", episodes: 5 },
      { title: "Season 26: Marilyn", episodes: 5 },
      { title: "Season 27: Saint Dolly", episodes: 4 },
      { title: "Season 28: Still Standing", episodes: 5 },
      { title: "Season 29: Back to Bennifer", episodes: 2 },
      { title: "Season 30: Fresh Prince to Fallen King", episodes: 6 },
      { title: "Season 31: JFK & Jackie", episodes: 3 },
      { title: "Season 32: Rewriting The Story", episodes: 5 },
      { title: "Season 33: In God We Lust", episodes: 2 },
    ],
  },
  {
    id: "8514",
    seasonDetails: [
      { title: "Season 1: Thai Cave Rescue", episodes: 6 },
      { title: "Season 2: Kidnapped in the Desert", episodes: 4 },
      { title: "Season 3: Prisoner of War", episodes: 5 },
      { title: "Season 4: The Savage Mountain", episodes: 5 },
      { title: "Season 5: Shipwreck on the Sahara", episodes: 5 },
      { title: "Season 6: Surviving Antarctica", episodes: 6 },
      { title: "Season 7: Plane Crash in the Andes", episodes: 5 },
      { title: "Season 8: Chilean Mine Collapse", episodes: 5 },
      { title: "Season 9: Rock Climbers Abducted", episodes: 5 },
      { title: "Season 10: Disaster at Sea", episodes: 5 },
      { title: "Season 11: Stranded in the Arctic", episodes: 3 },
      { title: "Season 12: Kidnapped in the Desert", episodes: 3 },
      { title: "Season 13: Avalanche at Tunnel Creek", episodes: 2 },
      { title: "Season 14: Meltdown at Fukushima", episodes: 5 },
      { title: "Season 15: Trapped on Mount Hood", episodes: 6 },
      { title: "Season 16: Thai Cave Rescue", episodes: 5 },
      { title: "Season 17: Crash in a Volcano", episodes: 3 },
      { title: "Season 18: Wildfire in Paradise", episodes: 6 },
      { title: "Season 19: The Race to Save Squalus", episodes: 1 },
    ],
  },
  {
    id: "10276",
    seasonDetails: Array.from({ length: 5 }, (_, i) => ({
      title: `Season ${i + 1}`,
      episodes: 10,
    })),
  },
  {
    id: "8860",
    seasonDetails: [
      { title: "Season 1: The Litvinenko Affair", episodes: 5 },
      { title: "Season 2: The Sexed Up Dossier", episodes: 4 },
      { title: "Season 3: The Murdoch Phone Hacking", episodes: 5 },
      { title: "Season 4: Breaking Barings", episodes: 4 },
      { title: "Season 5: The Profumo Affair", episodes: 6 },
      { title: "Season 6: The Canoe Con", episodes: 4 },
      { title: "Season 7: Anarchy In The UK (Sex Pistols)", episodes: 5 },
      { title: "Season 8: Lord Lucan", episodes: 4 },
      { title: "Season 9: The Litvinenko Affair", episodes: 5 },
      { title: "Season 10: The Coughing Major", episodes: 4 },
      { title: "Season 11: Maxwell", episodes: 5 },
      { title: "Season 12: Spy Cops", episodes: 4 },
      { title: "Season 13: Archer", episodes: 4 },
      { title: "Season 14: Hatton Garden", episodes: 4 },
      { title: "Season 15: Hitler Diaries", episodes: 4 },
      { title: "Season 16: Abdication", episodes: 4 },
      { title: "Season 17: The Spy Who Came Back From The Dead", episodes: 4 },
      { title: "Season 18: The Queen of Clean", episodes: 4 },
      { title: "Season 19: Boris Johnson", episodes: 3 },
    ],
  },
  {
    id: "5629",
    seasonDetails: [
      { title: "Season 1: Rise of the Modern World", episodes: 10 },
      { title: "Season 2: The Later Middle Ages", episodes: 10 },
      { title: "Season 3: Early Modern Explosion", episodes: 10 },
      { title: "Season 4: Prehistory", episodes: 10 },
      { title: "Season 5: Classic Tides", episodes: 4 },
    ],
  },
];
